"use client"
import React from 'react'

const PaymentPage = ({ paymentData, titleButton }) => {
	return (
		<form
			className='w-full'
			method='post'
			action='https://secure.wayforpay.com/pay'
			acceptCharset='utf-8'
		>
			<input
				name='merchantAccount'
				value={paymentData.merchantAccount}
				readOnly
				type='hidden'
			/>
			<input
				name='merchantAuthType'
				value={paymentData.merchantAuthType}
				readOnly
				type='hidden'
			/>
			<input
				name='merchantDomainName'
				value={paymentData.merchantDomainName}
				readOnly
				type='hidden'
			/>
			<input
				name='orderReference'
				value={paymentData.orderReference}
				readOnly
				type='hidden'
			/>
			<input
				name='orderDate'
				value={paymentData.orderDate}
				readOnly
				type='hidden'
			/>
			<input name='amount' value={paymentData.amount} readOnly type='hidden' />
			<input
				name='currency'
				value={paymentData.currency}
				readOnly
				type='hidden'
			/>
			<input
				name='orderTimeout'
				value={paymentData.orderTimeout}
				readOnly
				type='hidden'
			/>
			{paymentData.productName.map((item, index) => (
				<input
					key={`product-name-${index}`}
					name='productName[]'
					value={item}
					readOnly
					type='hidden'
				/>
			))}
			{paymentData.productPrice.map((item, index) => (
				<input
					key={`product-price-${index}`}
					name='productPrice[]'
					value={item}
					readOnly
					type='hidden'
				/>
			))}
			{paymentData.productCount.map((item, index) => (
				<input
					key={`product-count-${index}`}
					name='productCount[]'
					value={item}
					readOnly
					type='hidden'
				/>
			))}
			<input
				name='clientEmail'
				value={paymentData.clientEmail}
				readOnly
				type='hidden'
			/>
			<input
				name='defaultPaymentSystem'
				value={paymentData.defaultPaymentSystem}
				readOnly
				type='hidden'
			/>
			<input
				name='merchantSignature'
				value={paymentData.merchantSignature}
				readOnly
				type='hidden'
			/>
			<input
				name='serviceUrl'
				value={paymentData.serviceUrl}
				readOnly
				type='hidden'
			/>
			<input
				name='clientFirstName'
				value={paymentData.clientFirstName}
				readOnly
				type='hidden'
			/>
			<input
				name='clientLastName'
				value={paymentData.clientLastName}
				readOnly
				type='hidden'
			/>
			<input
				name='clientPhone'
				value={paymentData.clientPhone}
				readOnly
				type='hidden'
			/>
			<input
				name='orderLifetime'
				value={paymentData.orderLifetime}
				readOnly
				type='hidden'
			/>

			<button
				type='submit'
				className='w-full rounded-2xl border border-[#e2a550] bg-[#e2a550]/10 px-6 py-3 text-lg md:text-xl text-[#e2a550] hover:bg-[#e2a550]/20 duration-300'
			>
				{titleButton}
			</button>
		</form>
	)
}

export default PaymentPage
