// "use client"
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'
import bg from "../../public/phon.png"
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })


import { Providers } from '@/store/provider'


export const metadata = {
  title: 'School',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
		<html lang='en' className=' elem '>
			{/* <MovingCircle /> */}
			<body className={inter.className}>
				<div className='elem lg:min-h-screen  relative scroll flex flex-col justify-between px-[3%]'>
					<Image
						src={bg}
						alt='bg'
						fill
						priority={true}
						className='object-cover opacity-[0.8%]  '
					/>
					{/* <Provider store={store}> */}
					<Providers>
						<Header />
						<div className='flex-1'> {children}</div>
						<Footer />
					</Providers>
					{/* </Provider> */}
				</div>
			</body>
		</html>
	)
}
